In [26]:
import numpy as np
from numpy import linalg as LA

f = open("glove.6B.50d.txt", "r")
data = f.readlines()
i = 0
word = []
words = {}
Embeds = np.empty((len(data), len(data[0].split(' ')) - 1), dtype=np.double)
for line in data:
    splitted = line.split(" ")
    words[i] = splitted[0]
    Embeds[i] = (splitted[1:])
    i = i + 1

Embeds = Embeds / (LA.norm(Embeds, axis = 1).reshape(400000,1))

In [2]:
word = np.array(word)
i = np.where(word == "cool") [0][0]
scal = np.matmul(Embeds[i], Embeds.T)
J = np.argsort(scal)

s = list(word[J[-26:]])
s.reverse()
maxes = scal[J[-26:]]
maxes = (np.abs(2 - 2*maxes))**(0.5)
maxes = list(maxes)
maxes.reverse()
s = list(map(str,s))
list2Str = ""
for k in range(26):
    list2Str = list2Str + s[k] + "[" + str(round(maxes[k],5)) + "] "
list2Str

'cool[0.0] hot[0.5282] warm[0.61523] cold[0.61587] bit[0.64275] dry[0.68327] cooler[0.69001] little[0.69308] mix[0.70241] soft[0.71362] bright[0.71786] pretty[0.72061] chill[0.72808] looks[0.73225] wet[0.74029] sunny[0.74979] look[0.75038] too[0.75077] touch[0.75435] thin[0.75893] dark[0.76325] hard[0.77023] tends[0.77686] keeps[0.77689] smooth[0.77752] heat[0.77877] '

In [6]:
z = zip(J//400000, J%400000)
print(list(z))
scal[J]

[(70, 1085), (54, 94), (94, 54), (55, 228), (55, 174), (34, 413), (30, 36), (81, 769), (27, 28), (36, 30), (87, 739), (94, 414), (28, 27), (73, 56), (56, 73), (87, 502), (87, 438), (55, 133), (87, 55), (87, 228), (55, 87), (87, 133), (23, 24), (87, 174), (24, 23)]


array([0.95894204, 0.96037266, 0.96037266, 0.96413123, 0.96446624,
       0.96080608, 0.96512837, 0.96606756, 0.97268178, 0.96512837,
       0.97082669, 0.96715802, 0.97268178, 0.97511242, 0.97511242,
       0.97698298, 0.98134176, 0.98174724, 0.98859015, 0.9858181 ,
       0.98859015, 0.9942331 , 0.99509494, 0.98951072, 0.99509494])

In [74]:
i = 0
max_vals = []
for i in range(4000):
    scal = np.matmul(Embeds[i*100:(i+1)*100], Embeds.T)
    scal = np.triu(scal, i*100+1)
    scal = np.ravel(scal)
    J = np.argpartition(scal, (-25, -1))[-25:]
    J_local = np.array(list(zip(J//400000 + i * 100, J%400000)))
    current_vals = scal[J]
    J_local = np.flip(J_local, axis=0)
    current_vals = np.flip(current_vals,axis=0)
#     print(J_local)
#     print(current_vals)
    if i==0:
        max_ind = J_local
    else:
        max_ind = np.append(max_ind, J_local, axis=0)
        
    max_vals = np.append(max_vals, current_vals)
    J_new = np.argpartition(max_vals, (-25, -1))[-25:]
    max_vals = max_vals[J_new]
    max_ind = max_ind[J_new]
    
print(max_ind)
J_new = np.argsort(max_vals)
J_new = np.flip(J_new, axis=0)
max_vals = max_vals[J_new]
max_ind = max_ind[J_new]
for i in range(25):
    print('(' + words[max_ind[i,0]] + ', ' + words[max_ind[i,1]] + ' | ' + str(max_vals[i]) + ')')

[[   657    676]
 [   344    396]
 [322388 348373]
 [367870 367871]
 [   344    375]
 [359160 359161]
 [ 27122  28770]
 [  1076   1086]
 [   947    952]
 [ 28770  29535]
 [   478    617]
 [   177    183]
 [   441    478]
 [   171    183]
 [ 33448  34934]
 [   171    184]
 [260973 281350]
 [   177    184]
 [ 23684  25568]
 [ 21912  23684]
 [   183    184]
 [   171    177]
 [  1086   1094]
 [   375    396]
 [345721 345722]]
(piyanart, srivalo | 0.999895918380112)
(artthielseattle, lauravecseyseattle | 0.9982480316676561)
(ba632, ba633 | 0.9981987474148983)
(tuesday, monday | 0.9981015491425101)
(tuesday, thursday | 0.997851731352666)
(tuesday, wednesday | 0.9977707917837518)
(monday, thursday | 0.9976342564249955)
(formula_4, formula_5 | 0.9976102258531189)
(formula_5, formula_6 | 0.9972320296874572)
(wednesday, thursday | 0.9971067630156977)
(gmathis, sksmith | 0.9968831788254773)
(june, july | 0.9965305312552686)
(formula_12, formula_13 | 0.9964950669677369)
(september, october | 0.996

In [75]:
print(max_ind)

[[345721 345722]
 [322388 348373]
 [367870 367871]
 [   171    183]
 [   171    184]
 [   171    177]
 [   183    184]
 [ 21912  23684]
 [ 23684  25568]
 [   177    184]
 [260973 281350]
 [   344    375]
 [ 33448  34934]
 [   441    478]
 [ 27122  28770]
 [   177    183]
 [   478    617]
 [   947    952]
 [ 28770  29535]
 [  1076   1086]
 [359160 359161]
 [  1086   1094]
 [   375    396]
 [   344    396]
 [   657    676]]


In [6]:
list(word)

['the',
 ',',
 '.',
 'of',
 'to',
 'and',
 'in',
 'a',
 '"',
 "'s",
 'for',
 '-',
 'that',
 'on',
 'is',
 'was',
 'said',
 'with',
 'he',
 'as',
 'it',
 'by',
 'at',
 '(',
 ')',
 'from',
 'his',
 "''",
 '``',
 'an',
 'be',
 'has',
 'are',
 'have',
 'but',
 'were',
 'not',
 'this',
 'who',
 'they',
 'had',
 'i',
 'which',
 'will',
 'their',
 ':',
 'or',
 'its',
 'one',
 'after',
 'new',
 'been',
 'also',
 'we',
 'would',
 'two',
 'more',
 "'",
 'first',
 'about',
 'up',
 'when',
 'year',
 'there',
 'all',
 '--',
 'out',
 'she',
 'other',
 'people',
 "n't",
 'her',
 'percent',
 'than',
 'over',
 'into',
 'last',
 'some',
 'government',
 'time',
 '$',
 'you',
 'years',
 'if',
 'no',
 'world',
 'can',
 'three',
 'do',
 ';',
 'president',
 'only',
 'state',
 'million',
 'could',
 'us',
 'most',
 '_',
 'against',
 'u.s.',
 'so',
 'them',
 'what',
 'him',
 'united',
 'during',
 'before',
 'may',
 'since',
 'many',
 'while',
 'where',
 'states',
 'because',
 'now',
 'city',
 'made',
 'like',
 